version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ~/data/mysql:/var/lib/mysql
      - ./provision/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: mysqld --character-set-server=latin1 --collation-server=latin1_swedish_ci
