const bcrypt = require('bcrypt')
const { pick } = require('lodash')
const { User, validate } = require('../models/users')
const mongoose = require('mongoose')
const express = require('express')
const router = express.Router()