export enum SupplyType {
  FE = 'FE',
  FU = 'FU',
  HE = 'HE',
  IN = 'IN',
  SeSo = 'SeSo',
  SePi = 'SePi',
  SeMa = 'SeMa',
  SeGi = 'SeGi',
  SeTr = 'SeTr',
  SeCo = 'SeCo',
  SeCe = 'SeCe',
  SeAl = 'SeAl',
  SeCa = 'SeCa',
  SeSor = 'SeSor',
  SeRG = 'SeRG',
  SeAv = 'SeAv',
  SeAr = 'SeAr',
  SeMan = 'SeMan',
  SeCen = 'SeCen',
  SeArr = 'SeArr',
  Otros = 'Otros'
}
