export const codeIntegrations = [
  'COMPANY_NOT_FOUND',
  'COMPANY_PREVIOUSLY_CREATED',
  'COULD_NOT_CONNECT_WITH_UCROPIT',
  'CROP_HAS_BEEN_PREVIOUSLY_EXPORTED',
  'ERP_AGENT_NOT_IMPLEMENTED',
  'MODEL_NOT_DEFINED',
  'THE_LOT_HAS_NOT_BEEN_PREVIOUSLY_EXPORTED',
  'THE_REALIZATION_DOES_NOT_HAVE_LOTS',
  'THE_REALIZATION_DOES_NOT_HAVE_SUPPLIES',
  'THE_USERS_TOKEN_IS_INVALID_EXCEPTION',
  'UCROPIT_CROP_NOT_FOUND',
  'INVALID_CREDENTIALS_OF_USER_AURAVANT',
  'UNAUTHORIZED'
]
