export enum BadgeTypes {
  LEGAL_LAND_USE= 'LEGAL_LAND_USE',
  NO_DEFORESTATION= 'NO_DEFORESTATION',
  SUSTAINABLE_PRINCIPLES= 'SUSTAINABLE_PRINCIPLES',
  LEGAL_SEED_USE= 'LEGAL_SEED_USE',
  RESPOSIBLE_USE_PHYTOSANITARY= 'RESPOSIBLE_USE_PHYTOSANITARY',
}