export enum UserTypes {
  PRODUCER = 'PRODUCER',
  PRODUCER_ADVISER = 'PRODUCER_ADVISER',
  PRODUCER_ADVISER_ENCOURAGED = 'PRODUCER_ADVISER_ENCOURAGED',
  MARKETER = 'MARKETER',
  PROVIDER = 'PROVIDER',
  CAM = 'CAM',
  KAM = 'KAM'
}
