export enum TypeActivities {
  ACT_SOWING= 'ACT_SOWING',
  ACT_APPLICATION= 'ACT_APPLICATION',
  ACT_TILLAGE= 'ACT_TILLAGE',
  ACT_FERTILIZATION= 'ACT_FERTILIZATION',
  ACT_MONITORING= 'ACT_MONITORING',
  ACT_HARVEST= 'ACT_HARVEST',
  ACT_AGREEMENTS= 'ACT_AGREEMENTS'
}