export const ReportsEiqHeaderXls = {
  fields: [
    'identifier',
    'companyName',
    'cropTypeName',
    'cropName',
    'activityTypeName',
    'ProvinceName',
    'CityName',
    'kmzLocation',
    'cropLotTag',
    'lotName',
    'supplieRegister',
    'supplieName',
    'supplieUnit',
    'supplieEiq',
    'scheduleDate',
    'supplieQuantity',
    'supplieEiqQuantity',
    'achievementDate',
    'supplieTotal',
    'lotSurface',
    'evidences',
  ],
  fieldNames: [
    'CUIT',
    'Empresa',
    'Cultivo',
    'Nombre de Campaña',
    'Labor',
    'Provincia',
    'Localidad',
    'Ubicación KMZ',
    'Campo',
    'Lote',
    'Registro Insumo',
    'Nombre Insumo',
    'Unidad',
    'EIQ Producto',
    'Fecha Planificada',
    'Dosis Plan',
    'EIQ Plan',
    'Fecha Realizacion',
    'Unidades Realizadas',
    'Ha Realizadas',
    'Evidencias',
  ]
}
