export const ReportsEiqHeaderXls = {
  fields: [
    'cropId',
    'activityId',
    'achievementId',
    'identifier',
    'companyName',
    'cropTypeName',
    'cropName',
    'activityTypeName',
    'ProvinceName',
    'CityName',
    'kmzLocation',
    'cropLotTag',
    'lotName',
    'supplieCode',
    'supplieId',
    'supplieName',
    'supplieUnit',
    'supplieEiq',
    'scheduleDate',
    'supplieQuantityPlanified',
    'supplieEiqPlanified',
    'achievementDate',
    'supplieTotal',
    'lotSurface',
    'evidences',
  ],
  fieldNames: [
    'CROP ID',
    'ACTIVITY ID',
    'ACHIEVEMENT ID',
    'CUIT',
    'Empresa',
    'Cultivo',
    'Nombre de Campaña',
    'Labor',
    'Provincia',
    'Localidad',
    'Ubicación KMZ',
    'Campo',
    'Lote',
    'Registro Insumo',
    'SUPPLY ID',
    'Nombre Insumo',
    'Unidad',
    'EIQ Producto',
    'Fecha Planificada',
    'Dosis Plan',
    'EIQ Plan',
    'Fecha Realizacion',
    'Unidades Realizadas',
    'Ha Realizadas',
    'Evidencias',
  ]
}
