export const ReportsXlsForEiqHeaderXls = {
  fields: [
    'cropId',
    'activityId',
    'achievementId',
    'identifier',
    'companyName',
    'cropTypeName',
    'cropName',
    'establishments',
    'lotName',
    'lotSurface',
    'kmzLocation',
    'achievementSuppliesId',
    'achievementSuppliesName',
    'achievementSuppliesUnit',
    'achievementSuppliesQuantity',
    'achievementSuppliesTotal',
    'achievementSupplyId',
    'achievementSupplyEiq',
    'achievementDate',
    'achievementSurface',
    'evidences',
    'activitySuppliesId',
    'activitySuppliesUnit',
    'activitySuppliesQuantity',
    'activitySuppliesTotal',
    'activitySuppliesEiq',
    'activityDateStart',
    'activitySurface'
  ],
  fieldNames: [
    'CROP ID',
    'ACTIVITY ID',
    'ACHIEVEMENT ID',
    'CUIT',
    'Nombre de empresa',
    'Tipo de cultivo',
    'Nombre de Campaña',
    'Establecimientos',
    'Nombre del lote',
    'Superficie del lote',
    'Ubicación del KMZ',
    'Supplies ID (Realización)',
    'Supplies Nombre (Realización)',
    'Supplies Unidad (Realización)',
    'Supplies Cantidad (Realización)',
    'Supplies Total (Realización)',
    'Supply ID (Realización)',
    'Supply EIQ (Realización)',
    'Fecha de Realizacion',
    'Superficie de Realizacion',
    'Evidencias',
    'Supplies ID (Planificación)',
    'Supplies Unidad (Planificación)',
    'Supplies Cantidad (Planificación)',
    'Supplies Total (Planificación)',
    'Supplies EIQ (Planificación)',
    'Fecha de Planificación',
    'Superficie de Planificación'
  ]
}
